pool:
  vmImage: 'Ubuntu 16.04'

pr:
  - master

trigger:
  - master

steps:
  - script: ./fake.sh build
  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'